### PR TITLE
Add some message for help with code

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by ghost** [comment]
Not quite sure if the code works, added a comment in the Readme

**Comment by choonhongyeoh0241** [comment]
I can make a restriction system but need some time to work on the complete quest system in my way. And would like to share it with you in this repository since I got the idea from your side if possible

**Comment by choonhongyeoh0241** [comment]
Sorry I didn't see your message but I would like to show my works and work together on improving it as Game development is my interest and hobby

**Comment by choonhongyeoh0241** [comment]
However, I do have one question on the timeline cutscene, I would like to learn if possible

**Review by choonhongyeoh0241 — COMMENTED** [review]
I've sent you an email and comment in the pull request as well

**Pull request merged**
